### ISSUE TITLE
Convert dataset to jsonl format and split the dataset to train and test sets

### ISSUE THREAD

**Issue by akshatchhabra** [akshatchhabra/TransLRPL#1]
Currently all code snippets reside in different files. Merge all the files into a jsonl file to use it for training TransCoder. Details can be found here: https://github.com/facebookresearch/CodeGen/issues/76

**Comment by vedasreeb29** [comment]
The accepted code snippets for C# and Ruby were extracted from the Project CodeNet dataset. The submissions for a particular problem in a particular language are merged into separate jsonl files, which can be used to train TransCoder.

**Comment by vedasreeb29** [comment]
The dataset is split into train and test sets according to below 
Train dataset - 80% of the problems extracted from the total problems available
Test dataset 1 - 30% part of submissions from the problems in train set
Test dataset 2 - 20% of the problems extracted from the total problems available
