### ISSUE TITLE
Implement LangProcessors for C# and Ruby

### ISSUE THREAD

**Issue by rahulv98** [akshatchhabra/TransLRPL#6]
Extend [TreeSitterLangProcessor](https://github.com/facebookresearch/CodeGen/blob/6e93aca63e7bc77287c9965a5080456326651237/codegen_sources/preprocessing/lang_processors/tree_sitter_processor.py) and create LangProcessors for C# and Ruby to parse and preprocess(filter and tokenize) the data. 

Example: [JavaProcessor](https://github.com/facebookresearch/CodeGen/blob/6e93aca63e7bc77287c9965a5080456326651237/codegen_sources/preprocessing/lang_processors/java_processor.py)

**Comment by akshatchhabra** [comment]
Implemented the processors. They can be found in the c-sharp-processor branch.
C# processor: https://github.com/akshatchhabra/TransLRPL/blob/c-sharp-processor/CodeGen/codegen_sources/preprocessing/lang_processors/c-sharp_processor.py
Ruby processor: https://github.com/akshatchhabra/TransLRPL/blob/c-sharp-processor/CodeGen/codegen_sources/preprocessing/lang_processors/ruby_processor.py
